studentname=input("Enter Student name")
studntage=int(input("Enter student age"))
courserating=float(input("Enter course ratingni"))
print("Student:",studentname)
print("Age:",studntage)
print("Rating:",courserating)
print(type(studentname))
print(type(studntage))
print(type(courserating))